baseURL: "https://kaylum.github.io"
languageCode: "en-us"
title: "kaylum.io"
theme: hugo-profile

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  #main:
  # - identifier: blog
  #   name: Blog
  #   title: Blog posts
  #   url: /blogs
  #   weight: 1

  # - identifier: gallery
  #   name: Gallery
  #   title: Blog posts
  #   url: /gallery
  #   weight: 2

  #Dropdown menu
  # - identifier: dropdown
  #   title: Example dropdown menu
  #   name: Dropdown
  #   weight: 3
  # - identifier: dropdown1
  #   title: example dropdown 1
  #   name: example 1
  #   url: /#
  #   parent: dropdown
  #   weight: 1
  # - identifier: dropdown2
  #   title: example dropdown 2
  #   name: example 2
  #   url: /#
  #   parent: dropdown
  #   weight: 2

params:
  title: "kaylum.io"
  description: Personal site for Calem Roelofs
  # staticPath: "static" # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Calem Roelofs."
    subtitle: "I like solving problems."
    content: "I write full-stack web applications using Golang, Python, React.js and React Native so I can buy toys for my cats."
    image: "/images/cat.jpg"
    button:
      enable: false
      name: "Resume"
      url: "/Resume-Calem-Roelofs.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/CalemRoelofs
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/calemroelofs/
        - icon: fas fa-envelope
          url: mailto:hello@kaylum.io

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/cat2.jpg"
    content: |-
      I'm a software developer with a passion for all facets of modern web development.   
      Whether I'm designing scalable microservices, optimizing GraphQL field functions, or centering divs on the frontend, I'm at my happiest when I'm tinkering.  
      I'm currently working as a full-stack developer at [Samsara](https://samsara.com/), focusing on dispatch routing.  
      I am a native English speaker and also speak Polish at an A2 level.
    skills:
      enable: true
      title: "Here's some of the technologies I'm working with at the moment:"
      items:
        - "Golang"
        - "TypeScript"
        - "React"
        - "Python"
        - "MySQL"
        - "gRPC"
        - "GraphQL"
        - "AWS"

  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineer II"
        company: "Samsara"
        companyUrl: "https://samsara.com/"
        date: "May 2024 - Present"
        featuredLink:
          enable: false
        info:
          enable: false
        content: |
          - Writing full-stack features in a microservices environment for both web and mobile clients
          - Working closely with both product and engineering to design new features and meet customer demands
          - Profiling and optimizing query performance across federated GraphQL and sharded MySQL infrastructure 
          - Performing data analysis with Python and Databricks to drive business decisions
      - job: "Software Engineer"
        company: "SmartBear"
        companyUrl: "https://smartbear.com/"
        date: "Dec 2021 - Apr 2024"
        featuredLink:
          enable: false
        info:
          enable: false
        content: |
          - Wrote, reviewed, and maintained code for Java and Node.js microservices
          - Introduced tracing and observability with DataDog APM to preemptively catch performance issues and outages
          - Contributed to numerous open-source projects under the [Swagger](https://github.com/swagger-api) brand, such as [Swagger Parser](https://github.com/swagger-api/swagger-parser) and [ApiDOM](https://github.com/swagger-api/apidom)
          - Led a data engineering project for gathering and aggregating metrics for SmartBear's OSS products with Dagster and Apache Superset
      - job: "Software Engineer"
        company: "Viatel"
        companyUrl: "https://www.viatel.com/"
        date: "Aug 2021 - Dec 2021"
        featuredLink:
          enable: false
        info:
          enable: false
        content: |
          - Worked on internal and customer-facing applications using C#/.NET
          - Migrated team to fully CI/CD using Azure DevOps
          - Helped to increase test coverage and improve processes
      - job: "Technical Support Agent"
        company: "Viatel"
        companyUrl: "https://www.viatel.com/"
        date: "Mar 2021 - Aug 2021"
        info:
          enable: false
        featuredLink:
          enable: false
        content: |
          - Supported SME customer's internet, voice and cloud infrastructure
          - Diagnosed issues by working with customers over the phone
          - Automated some repetitive processes using Python
      - job: "Technical Support Agent"
        company: "Ripplecom"
        companyUrl: "https://www.viatel.com/ripplecom"
        date: "Jan 2020 - Mar 2021"
        featuredLink:
          enable: false
        info:
          enable: true
          content: "Note: Ripplecom were acquired by Viatel in late 2020 and no longer exist"
        content: |
          - Supported residential and business customer's internet and voice connections
          - Performed troublshooting with customers where appropriate
          - Created several internal systems and integrations using Python
      - job: "Software Development Intern"
        company: "Ripplecom"
        companyUrl: "https://www.viatel.com/ripplecom"
        date: "Mar 2018 - Sep 2018"
        info:
          enable: true
          content: "Note: Ripplecom were acquired by Viatel in late 2020 and no longer exist"
        content: |
          - Designed, implemented and deployed a voice billing engine using Python and Flask
          - Worked closely with internal stakeholders to refine requirements and ensure satisfaction
          - Provided training and created documentation for customers and staff to use the new system

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "BSc. in Contemporary Software Development"
        school:
          name: "Atlantic Technological University (Formerly Letterykenny IT)"
          url: "https://www.atu.ie/"
        date: "2021 - 2021"
        GPA: "First Class Honours"

      - title: "NFQ Level 7 in Computer Networks & Systems Management"
        school:
          name: "Technological University of the Shannon (Formerly Limerick IT)"
          url: "https://tus.ie/"
        date: "2015 - 2018"
        GPA: "Merit"

  # Achievements
  achievements:
    enable: false

  # projects
  projects:
    enable: true
    items:
      - title: Czas
        content: |
          A Rust library built on top of chrono for converting timestamps into localized text
        image: /images/gh-avatar-1.png
        badges:
          - "Rust"
        links:
          - icon: fab fa-github
            url: https://github.com/CalemRoelofs/czas

      - title: Mieszkania we Wrocławiu
        content: An Jupyter notebook exploring the apartment rental market in Wrocław
        image: /images/gh-avatar-2.png
        featured:
          name: Notebook
          link: https://github.com/CalemRoelofs/mieszkania-wroclaw/blob/main/mieszkania.ipynb
        badges:
          - "Python"
          - "Pandas"
          - "Numpy"
        links:
          - icon: fab fa-github
            url: https://github.com/CalemRoelofs/mieszkania-wroclaw

      - title: Quotemaker
        content: A program to generate non-sensical inspirational quote images with markov chains.
        image: /images/gh-avatar-3.png
        badges:
          - "Python"
          - "Markov Chains"
        links:
          - icon: fab fa-github
            url: https://github.com/CalemRoelofs/Quotemaker

  #Contact
  contact:
    enable: true
    content: Got a question about programming, music or cats?
    email: hello@kaylum.io
    btnName: Send me an email

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/CalemRoelofs
      linkedin: https://linkedin.com/in/calemroelofs
      email: hello@kaylum.io
